### ISSUE TITLE
Enable wildcard namespace definition when setting namespace RPS

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/temporal#114]
**Is your feature request related to a problem? Please describe.**
It seems there is a way of setting namespace RPS limits as [outlined here](https://community.temporal.io/t/rate-limiting-by-namespace/1335/7). To enable a more dynamic approach, it would be useful to be able to define wildcard rules that get applied to namespaces (e.g. `stg-*` means any namespaces matching this rule such as `stg-test` will have this rule applied to it).

**Describe the solution you'd like**
Current functionality:
```yaml
frontend.namespacerps:
- value: 2000
- value: 100
  constraints:
    namespace: "namespaceA"
- value: 500
  constraints:
    namespace: "namespaceB"
```

Requested functionality:
```yaml
frontend.namespacerps:
- value: 1000
- value: 500
  constraints:
    namespace: "stg-*"
- value: 600
  constraints:
    namespace: "prod-*"
```

**Describe alternatives you've considered**
The alternative here is updating the server config every time a new namespace is added to which we want to apply RPS limits. The proposed approach can allow a more generic configuration of RPS limits to namespaces.

**Additional context**
N/A

**Comment by dhiaayachi** [comment]
## Is your feature request related to a problem? Please describe.

It seems that there is a way of setting namespace RPS limits as [outlined here](https://community.temporal.io/t/rate-limiting-by-namespace/1335/7).  To enable a more dynamic approach, it would be useful to be able to define wildcard rules that get applied to namespaces (e.g. `stg-*` means any namespaces matching this rule such as `stg-test` will have this rule applied to it).

## Describe the solution you'd like

Currently, the dynamic configuration allows namespace-specific limits to be defined like this:

```yaml
frontend.namespacerps:
- value: 2000
- value: 100
  constraints:
    namespace: "namespaceA"
- value: 500
  constraints:
    namespace: "namespaceB"
```

The proposed change would allow for wildcard rules in the `namespace` constraint:

```yaml
frontend.namespacerps:
- value: 1000
- value: 500
  constraints:
    namespace: "stg-*"
- value: 600
  constraints:
    namespace: "prod-*"
```

## Describe alternatives you've considered

The alternative here is updating the server config every time a new namespace is added to which we want to apply RPS limits. The proposed approach can allow a more generic configuration of RPS limits to namespaces.

## Additional context

N/A

**Comment by dhiaayachi** [comment]
Thanks for the feature request. It's a great suggestion! Currently, Temporal doesn't support wildcard rules for namespace RPS limits. 

As a workaround, you can achieve a similar effect by using a  [dynamic configuration](/references/dynamic-configuration) with a `namespace` constraint,  but you'll have to update the configuration file manually every time you create a new namespace.

Here's an example of a dynamic configuration file:

```yaml
frontend.namespacerps:
- value: 1000
- value: 500
  constraints:
    namespace: "stg-*"
- value: 600
  constraints:
    namespace: "prod-*"
```

The dynamic configuration file can be loaded into your Temporal server using the `dynamicConfigClient` section in your configuration file: 

```yaml
dynamicConfigClient:
  filepath: "path/to/dynamic-config.yaml"
  pollInterval: "10s"
```
