### ISSUE TITLE
Temporal can't connect to Elasticsearch with enabled TLS

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/temporal#324]
## Expected Behavior
Temporal cluster establishes connection with  Elasticsearch.

## Actual Behavior
"no ElasticSearch node available"

## Steps to Reproduce the Problem
  1. Setup elastic 8 version with enabled TLS on the HTTP layer
  2. Set `scheme: "https"` in Temporal server config
```yaml
        elasticsearch:
          version: "v8"
          url:
            scheme: "https"
```

## Specifications

  - Temporal Version: 1.21.3
  - Elasticsearch Version: 8.6.2
  - Platform: Kubernetes
