### ISSUE TITLE
UI cannot be displayed in IFrame - possibly bcs. CORS

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/temporal#369]
## Expected Behavior
Temporal UI should be displayed in an iframe of another application when CORS is set to '*'.

## Actual Behavior
Content is blocked. Iframe is empty

## Steps to Reproduce the Problem

  1. Setup temporal with docker environment. Set the corresponding environment variables like so in docker-compose.yml
  ```
[...]
temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=*
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      - 8080:8080
[...]
```
  2. Access the exposed port via an iframe.
  3. IFrame reports blocked content.

## Specifications

  - Version: 
TEMPORAL_VERSION=1.20.2
TEMPORAL_UI_VERSION=2.13.3
  - Platform: 
Linux / Google Kubernetes Engine

I want to use the UI as part of a dashboard beacause here I have the benefit of not having the user authenticate in temporal, but beforehand in the dashboard. Therefor I want to display the UI inside it, hence the IFrame.

Thank you for sharing this great piece of software. 
Suggestions appreciated.
