### ISSUE TITLE
GKE Web UI 404 Archival Using bucket

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/temporal#41]
## Web UI 404 when accessing detail of workflow id from archival
![image](https://github.com/user-attachments/assets/d93e3b8f-5847-4578-810e-dcd0080bf06b)

Here is the English translation of your issue:

---

I am using Helm to deploy to GKE with the `values.archival.gcloud.yaml` as follows:

```yaml
server:
  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        gstorage:
          credentialsPath: "/etc/credentials/credentials.json"
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        gstorage:
          credentialsPath: "/etc/credentials/credentials.json"

  namespaceDefaults:
    archival:
      history:
        state: "enabled"
        URI: "gs://kp-temporal-archival/temporal_archival"
      visibility:
        state: "enabled"
        URI: "gs://kp-temporal-archival/temporal_visibility"
```

For persistence, I am using PostgreSQL with the following `values.postgresql.yaml`:

```yaml
server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: postgres.example.dev
          port: 5432
          database: temporal
          user: temporal
          password: temporal
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: postgres.example.dev
          port: 5432
          database: temporal_visibility
          user: temporal
          password: temporal
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true

prometheus:
  enabled: false

grafana:
  enabled: false
  
elasticsearch:
  enabled: true

schema:
  createDatabase:
    enabled: false
  setup:
    enabled: true
  update:
    enabled: true
```

Then, I forward the Web UI using Internal Ingress with the following configuration:

```yaml
web:
  enabled: true
  replicaCount: 1
  image:
    repository: temporalio/ui
    tag: 2.28.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    annotations: {}
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.regional-static-ip-name: ingress-temporal-web
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.class: "gce-internal"
    hosts:
      - "temporal.example.dev"
    tls:
      - secretName: temporal
        hosts:
          - temporal.example.dev
```

The archival and visibility files are already in the bucket.
![image](https://github.com/user-attachments/assets/164719ba-f231-4632-8156-bace700a6377)
![image](https://github.com/user-attachments/assets/ad638eaf-a003-49f2-824c-9054a0a07c69)
---
and this is my version server `1.24.2`

**Comment by dhiaayachi** [comment]
Thanks for reporting this issue!

Can you please provide the following information so I can help you further:

* What version of the Temporal UI are you using?
* Is there anything specific you've done to configure your Temporal server?  
* Do you have any custom components or configurations set up that could be contributing to this issue?

Once I have this information, I can try to find a solution based on the attached documents.

**Comment by dhiaayachi** [comment]
Let's break down the Temporal deployment process you described. Here's a comprehensive guide with explanations and recommendations:

**Introduction**

Temporal is a powerful workflow orchestration platform that helps build robust and scalable applications. The deployment process you described involves running Temporal as a standalone service with a reverse proxy for external access. This configuration provides flexibility and control over your workflow environment.

**Prerequisites**

Before you begin, make sure you have the following:

* **A Linux Server:** Temporal is primarily designed for Linux environments. You can use a cloud server (AWS EC2, Google Cloud VM, etc.) or a local Linux machine.
* **A Domain Name:** This is required for external access to your Temporal service. You can register a domain name through a registrar like GoDaddy, Namecheap, or Google Domains.
* **SSL Certificates:** For secure HTTPS connections, you'll need valid SSL certificates for your domain. You can obtain certificates through services like Let's Encrypt (using Certbot) or a domain registrar.
* **Basic Linux Knowledge:** Familiarity with the command line, file system navigation, and basic system administration tasks is helpful.

**Obtaining the Temporal Binaries**

* **Temporal Server:** Download the latest binary for your Linux system from the Temporal Github Releases page: [https://github.com/temporalio/temporal/releases/](https://github.com/temporalio/temporal/releases/)
* **Temporal UI Server:** Download the latest binary for your Linux system from the Temporal UI Server Github Releases page: [https://github.com/temporalio/ui-server/releases/](https://github.com/temporalio/ui-server/releases/)

**Configuring the Temporal Binaries**

1. **Temporal Server Configuration:** Create a `temporal-server.yaml` file in a directory of your choice (e.g., `/etc/temporal`). Here's a basic configuration that uses SQLite for persistence:

   ```yaml
   log:
     stdout: true
     level: info

   persistence:
     defaultStore: sqlite-default
     visibilityStore: sqlite-visibility
     numHistoryShards: 4
     datastores:
       sqlite-default:
         sql:
           pluginName: "sqlite"
           databaseName: "/etc/temporal/default.db"
           connectAddr: "localhost"
           connectProtocol: "tcp"
           connectAttributes:
             cache: "private"
             setup: true

       sqlite-visibility:
         sql:
           pluginName: "sqlite"
           databaseName: "/etc/temporal/visibility.db"
           connectAddr: "localhost"
           connectProtocol: "tcp"
           connectAttributes:
             cache: "private"
             setup: true

   global:
     membership:
       maxJoinDuration: 30s
       broadcastAddress: "127.0.0.1"
     pprof:
       port: 7936

   services:
     frontend:
       rpc:
         grpcPort: 7236
         membershipPort: 6933
         bindOnLocalHost: true
         httpPort: 7243

     matching:
       rpc:
         grpcPort: 7235
         membershipPort: 6935
         bindOnLocalHost: true

     history:
       rpc:
         grpcPort: 7234
         membershipPort: 6934
         bindOnLocalHost: true

     worker:
       rpc:
         membershipPort: 6939

   clusterMetadata:
     enableGlobalNamespace: false
     failoverVersionIncrement: 10
     masterClusterName: "active"
     currentClusterName: "active"
     clusterInformation:
       active:
         enabled: true
         initialFailoverVersion: 1
         rpcName: "frontend"
         rpcAddress: "localhost:7236"
         httpAddress: "localhost:7243"

   dcRedirectionPolicy:
     policy: "noop"
   ```

2. **Temporal UI Server Configuration:** Create a `temporal-ui-server.yaml` file in the same directory. Here's a basic configuration:

   ```yaml
   temporalGrpcAddress: 127.0.0.1:7236
   host: 127.0.0.1
   port: 8233
   enableUi: true
   cors:
     allowOrigins:
       - http://localhost:8233
   defaultNamespace: default
   ```

**Creating and Registering System Services**

1. **Temporal Server Service:** Create a `temporal.service` file in `/etc/systemd/system/`. This file defines the Temporal server as a system service:

   ```yaml
   [Unit]
   Description=Temporal Service
   After=network.target

   [Service]
   User=temporal
   Group=temporal
   ExecStart=/usr/bin/temporal-server -r / -c /etc/temporal/ -e temporal-server start

   [Install]
   WantedBy=multi-user.target
   ```

   * **Important:** Replace `/usr/bin/temporal-server` with the actual path where you placed the downloaded Temporal server binary.

2. **Temporal UI Server Service:** Create a `temporal-ui.service` file in `/etc/systemd/system/`:

   ```yaml
   [Unit]
   Description=Temporal UI Server
   After=network.target

   [Service]
   User=temporal
   Group=temporal
   ExecStart=/usr/bin/temporal-ui-server -r / -c /etc/temporal/ -e temporal-ui-server start

   [Install]
   WantedBy=multi-user.target
   ```

   * **Important:** Replace `/usr/bin/temporal-ui-server` with the actual path where you placed the downloaded UI server binary.

3. **Enable and Start Services:**

   ```bash
   sudo systemctl enable temporal
   sudo systemctl start temporal

   sudo systemctl enable temporal-ui
   sudo systemctl start temporal-ui
   ```

**Deploying an Nginx Reverse Proxy with an SSL Certificate**

1. **Install Nginx:** If Nginx is not already installed, use your Linux distribution's package manager to install it. For example, on Ubuntu/Debian:

   ```bash
   sudo apt update
   sudo apt install nginx
   ```

2. **Obtain SSL Certificates (Certbot):**  Use Certbot to automatically obtain and install SSL certificates from Let's Encrypt:

   ```bash
   sudo apt install certbot
   sudo certbot certonly --standalone -d YOUR_DOMAIN
   ```

   * Replace `YOUR_DOMAIN` with your actual domain name.

3. **Nginx Configuration (Temporal UI):** Create a `temporal-ui` configuration file in `/etc/nginx/sites-available/`:

   ```nginx
   server {
       listen 80 default_server;
       listen [::]:80 default_server;
       server_name YOUR_DOMAIN www.YOUR_DOMAIN

       access_log /var/log/nginx/temporal.access.log;
       error_log /var/log/nginx/temporal.error.log;

       location / {
           proxy_pass http://127.0.0.1:8233;
           proxy_http_version 1.1;
           proxy_read_timeout 300;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";
           proxy_set_header Host $http_host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Real-PORT $remote_port;
           # Replace with your allowed client IPs
           allow 192.168.1.100;
           deny all;
       }

       listen 443 ssl;
       ssl_certificate /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem;
       ssl_certificate_key /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem;

       # Redirect non-https traffic to https
       if ($scheme != "https") {
           return 301 https://$host$request_uri;
       }
   }
   ```

   * **Important:** Replace `192.168.1.100` with your allowed client IP address(es) or IP range. 

4. **Nginx Configuration (Temporal gRPC):** Create a `temporal` configuration file in `/etc/nginx/sites-available/`:

   ```nginx
   server {
       listen 7233 http2;
       listen [::]:7233 http2;
       server_name YOUR_DOMAIN

       http2 on;

       location / {
           grpc_pass localhost:7236;
           # Replace with your allowed client IPs
           allow 192.168.1.100;
           deny all;
       }
   }
   ```

   * **Important:** Replace `192.168.1.100` with your allowed client IP address(es) or IP range (same as for Temporal UI).

5. **Enable and Reload Nginx:**

   ```bash
   sudo ln -s /etc/nginx/sites-available/temporal-ui /etc/nginx/sites-enabled/temporal-ui
   sudo ln -s /etc/nginx/sites-available/temporal /etc/nginx/sites-enabled/temporal

   sudo systemctl reload nginx
   ```

**Interacting with the Temporal Service**

* **Temporal Web UI:**  Open your web browser and navigate to `https://YOUR_DOMAIN`.
* **Temporal CLI:** Use the Temporal CLI to interact with your Temporal service from the command line. Remember to include the `--address your_server:7233` flag in your CLI commands.

**Conclusion**

By following these steps, you've successfully deployed a Temporal service with an Nginx reverse proxy and SSL certificate. This configuration provides a secure and scalable environment for your workflows. 

**Key Points:**

* **Security:**  Always prioritize security. Use IP-based access control with Nginx, and consider using Temporal's authentication features for production deployments.
* **Monitoring:** Monitor your Temporal service logs regularly to identify any issues and ensure smooth workflow operation.
* **Scalability:** For large-scale deployments, consider using Temporal's high-availability (HA) options and a more robust persistence solution like MySQL or PostgreSQL.

Feel free to ask if you have any further questions! Let me know if you'd like help with specific workflows, the Temporal CLI, or other aspects of the deployment.
