### ISSUE TITLE
GKE Web UI 404 Archival Using bucket

### ISSUE THREAD

**Issue by dhiaayachi** [dhiaayachi/temporal#61]
## Web UI 404 when accessing detail of workflow id from archival
![image](https://github.com/user-attachments/assets/d93e3b8f-5847-4578-810e-dcd0080bf06b)

Here is the English translation of your issue:

---

I am using Helm to deploy to GKE with the `values.archival.gcloud.yaml` as follows:

```yaml
server:
  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        gstorage:
          credentialsPath: "/etc/credentials/credentials.json"
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        gstorage:
          credentialsPath: "/etc/credentials/credentials.json"

  namespaceDefaults:
    archival:
      history:
        state: "enabled"
        URI: "gs://kp-temporal-archival/temporal_archival"
      visibility:
        state: "enabled"
        URI: "gs://kp-temporal-archival/temporal_visibility"
```

For persistence, I am using PostgreSQL with the following `values.postgresql.yaml`:

```yaml
server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: postgres.example.dev
          port: 5432
          database: temporal
          user: temporal
          password: temporal
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: postgres.example.dev
          port: 5432
          database: temporal_visibility
          user: temporal
          password: temporal
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true

prometheus:
  enabled: false

grafana:
  enabled: false
  
elasticsearch:
  enabled: true

schema:
  createDatabase:
    enabled: false
  setup:
    enabled: true
  update:
    enabled: true
```

Then, I forward the Web UI using Internal Ingress with the following configuration:

```yaml
web:
  enabled: true
  replicaCount: 1
  image:
    repository: temporalio/ui
    tag: 2.28.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    annotations: {}
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.regional-static-ip-name: ingress-temporal-web
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.class: "gce-internal"
    hosts:
      - "temporal.example.dev"
    tls:
      - secretName: temporal
        hosts:
          - temporal.example.dev
```

The archival and visibility files are already in the bucket.
![image](https://github.com/user-attachments/assets/164719ba-f231-4632-8156-bace700a6377)
![image](https://github.com/user-attachments/assets/ad638eaf-a003-49f2-824c-9054a0a07c69)
---
and this is my version server `1.24.2`
